#!/usr/bin/env node
import { networkInterfaces } from "node:os";
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const API_PORT = 3001;
const PREFER_IFACES = ["en0", "en1", "eth0"];

export function isLanV4(addr) {
  return (
    (addr.family === "IPv4" || addr.family === 4) &&
    !addr.internal &&
    !addr.address.startsWith("169.254.")
  );
}

export function lanIp(ifaces = networkInterfaces()) {
  for (const name of PREFER_IFACES) {
    const hit = (ifaces[name] ?? []).find(isLanV4);
    if (hit) return hit.address;
  }
  for (const addrs of Object.values(ifaces)) {
    const hit = (addrs ?? []).find(isLanV4);
    if (hit) return hit.address;
  }
  return "127.0.0.1";
}

export function localApiUrl(ifaces = networkInterfaces()) {
  return `http://${lanIp(ifaces)}:${API_PORT}`;
}

export function envLocalContents(apiUrl) {
  return `# Generated by setup:env — LAN IP so simulator and physical devices can both reach the API.\nEXPO_PUBLIC_API_URL=${apiUrl}\n`;
}

export function writeEnvLocal(root, ifaces = networkInterfaces()) {
  const apiUrl = localApiUrl(ifaces);
  writeFileSync(path.join(root, ".env.local"), envLocalContents(apiUrl));
  const leftoverDotEnv = path.join(root, ".env");
  if (
    existsSync(leftoverDotEnv) &&
    readFileSync(leftoverDotEnv, "utf8").includes("Generated by setup:env")
  ) {
    unlinkSync(leftoverDotEnv);
  }
  return apiUrl;
}

function isDirectRun() {
  const entry = process.argv[1];
  if (!entry) return false;
  return import.meta.url === pathToFileURL(path.resolve(entry)).href;
}

if (isDirectRun()) {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const apiUrl = writeEnvLocal(root);
  if (apiUrl.includes("127.0.0.1")) {
    console.warn("No LAN IPv4 found; wrote 127.0.0.1. A physical device will not be able to reach the API.");
  }
  console.log(`Local API → ${apiUrl} (.env.local)`);
  console.log(`Archive API → .env.prod`);
}
