#!/usr/bin/env node
import { networkInterfaces } from "node:os";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(root, "../..");

function lanIp() {
  const ifaces = networkInterfaces();
  const prefer = ["en0", "en1", "eth0"];
  const isLan = (a) =>
    (a.family === "IPv4" || a.family === 4) && !a.internal && !a.address.startsWith("169.254.");
  for (const name of prefer) {
    const hit = (ifaces[name] ?? []).find(isLan);
    if (hit) return hit.address;
  }
  for (const addrs of Object.values(ifaces)) {
    const hit = (addrs ?? []).find(isLan);
    if (hit) return hit.address;
  }
  return "127.0.0.1";
}

function readEnv(file) {
  const out = {};
  if (!existsSync(file)) return out;
  for (const raw of readFileSync(file, "utf8").split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    let value = line.slice(eq + 1);
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[line.slice(0, eq)] = value;
  }
  return out;
}

const ip = lanIp();
const apiUrl = `http://${ip}:3001`;
const rootEnv = readEnv(path.join(repoRoot, ".env"));
const authUrl = process.env.EXPO_PUBLIC_NEON_AUTH_URL || rootEnv.EXPO_PUBLIC_NEON_AUTH_URL || rootEnv.VITE_NEON_AUTH_URL || "";

const lines = [
  `# Generated by setup:env — LAN IP so the phone can reach the API`,
  `EXPO_PUBLIC_API_URL=${apiUrl}`,
];
if (authUrl) lines.push(`EXPO_PUBLIC_NEON_AUTH_URL=${authUrl}`);

writeFileSync(path.join(root, ".env"), `${lines.join("\n")}\n`);
console.log(`Phone API → ${apiUrl}`);
