#!/usr/bin/env node
import { networkInterfaces } from "node:os";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function lanIp() {
  const ifaces = networkInterfaces();
  const prefer = ["en0", "en1", "eth0"];
  const isLan = (a) =>
    (a.family === "IPv4" || a.family === 4) && !a.internal && !a.address.startsWith("169.254.");
  for (const name of prefer) {
    const hit = (ifaces[name] ?? []).find(isLan);
    if (hit) return hit.address;
  }
  for (const addrs of Object.values(ifaces)) {
    const hit = (addrs ?? []).find(isLan);
    if (hit) return hit.address;
  }
  return "127.0.0.1";
}

const ip = lanIp();
const apiUrl = `http://${ip}:3001`;

writeFileSync(
  path.join(root, ".env"),
  `# Generated by setup:env — LAN IP so the phone can reach the API\nEXPO_PUBLIC_API_URL=${apiUrl}\n`,
);
console.log(`Phone API → ${apiUrl}`);
console.log(`Local Google OAuth callback → http://localhost:3001/api/auth/callback/google`);
console.log(`Production Google OAuth callback → https://relay-api-rsck.onrender.com/api/auth/callback/google`);
