import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, it } from "node:test";
import { envLocalContents, lanIp, localApiUrl, writeEnvLocal } from "../scripts/setup-env.mjs";

const wifi = {
  en0: [
    { family: "IPv6", address: "fe80::1", internal: false },
    { family: "IPv4", address: "192.168.1.82", internal: false },
  ],
  lo0: [{ family: "IPv4", address: "127.0.0.1", internal: true }],
};

describe("mobile setup-env", () => {
  it("picks the Mac LAN IPv4, not localhost", () => {
    assert.equal(lanIp(wifi), "192.168.1.82");
    assert.equal(localApiUrl(wifi), "http://192.168.1.82:3001");
    assert.doesNotMatch(localApiUrl(wifi), /localhost/);
  });

  it("skips link-local and loopback addresses", () => {
    assert.equal(
      lanIp({
        en0: [{ family: "IPv4", address: "169.254.12.4", internal: false }],
        en1: [{ family: "IPv4", address: "10.0.0.12", internal: false }],
      }),
      "10.0.0.12",
    );
    assert.equal(lanIp({ lo0: [{ family: "IPv4", address: "127.0.0.1", internal: true }] }), "127.0.0.1");
  });

  it("rewrites .env.local with the current LAN API URL", () => {
    const dir = mkdtempSync(path.join(tmpdir(), "relay-mobile-env-"));
    writeFileSync(path.join(dir, ".env.local"), "EXPO_PUBLIC_API_URL=http://localhost:3001\n");
    writeFileSync(path.join(dir, ".env"), "# Generated by setup:env\nEXPO_PUBLIC_API_URL=http://localhost:3001\n");
    const written = writeEnvLocal(dir, wifi);
    assert.equal(written, "http://192.168.1.82:3001");
    assert.equal(readFileSync(path.join(dir, ".env.local"), "utf8"), envLocalContents(written));
    assert.throws(() => readFileSync(path.join(dir, ".env")));
  });
});
